---
prod:
  hosts:
    tebe:
      ansible_host: "{{ lookup('ansible.builtin.env', 'DEPLOY_HOST', default='tebe.local.zabik') }}"
      ansible_port: "{{ lookup('ansible.builtin.env', 'DEPLOY_PORT', default='22222') }}"
      ansible_user: "{{ lookup('ansible.builtin.env', 'DEPLOY_USER', default='mamayra') }}"
